In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

class ModelSharpe(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(ModelSharpe, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.linear = nn.Linear(hidden_size, output_size)

    def _sharpe_loss(self, portfolio_returns):
        mean_returns = portfolio_returns.mean(dim=1)
        std_returns = portfolio_returns.std(dim=1) + 1e-6
        sharpe_ratio = mean_returns / std_returns
        return -sharpe_ratio.mean()

    def forward(self, x, y):
        output_lstm, (hn, cn) = self.lstm(x)
        unnormalized_weights = self.linear(output_lstm)
        weights = torch.softmax(unnormalized_weights, dim=-1)
        portfolio_returns = torch.sum(weights[:, :, :] * y[:, :, :], dim=2)
        loss = self._sharpe_loss(portfolio_returns)
        return loss

    def get_allocations(self, x):
        with torch.no_grad():
            output_lstm, (hn, cn) = self.lstm(x)
            unnormalized_weights = self.linear(output_lstm)
            weights = torch.softmax(unnormalized_weights, dim=-1)
        return weights[:, -1, :]


In [3]:
random_tensor = 2 * torch.rand(1, 50, 5) - 1
y = 2 * torch.rand(1, 50, 5) - 1

In [4]:
model_lstm = ModelSharpe(5, 64, 5)

In [5]:
A = model_lstm(random_tensor, y)
print(A.shape, A)
print(model_lstm.get_allocations(random_tensor))

torch.Size([]) tensor(0.1113, grad_fn=<NegBackward0>)
tensor([[0.2001, 0.1915, 0.2028, 0.2169, 0.1887]])


In [6]:
import numpy as np
import yfinance as yf
import pandas as pd

tickers = ['VTI', 'AGG', 'DBC', '^VIX']
data = yf.download(tickers, start="2006-01-01", end="2020-12-31", interval="1d")['Adj Close']
data_na = data.dropna(axis = 0)
for column in data_na.columns:
    data_na[f'{column}_R'] = data_na[f'{column}'].pct_change()
    data_na[f'{column}_y'] = data_na[f'{column}_R'].shift(-1)
data_na.dropna(axis=0, inplace=True)
data_na.reset_index(inplace=True)
data_na['Date'] = data_na['Date'].dt.date
data_na

[*********************100%***********************]  4 of 4 completed
/var/folders/7q/v0vj3h051dn717mx7ngrr8yh0000gn/T/ipykernel_70529/2234399925.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_na[f'{column}_R'] = data_na[f'{column}'].pct_change()
/var/folders/7q/v0vj3h051dn717mx7ngrr8yh0000gn/T/ipykernel_70529/2234399925.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_na[f'{column}_y'] = data_na[f'{column}_R'].shift(-1)
/var/folders/7q/v0vj3h051dn717mx7ngrr8yh0000gn/T/ipykernel_70529/2234

Ticker        Date         AGG        DBC         VTI       ^VIX     AGG_R  \
0       2006-02-07   56.262363  20.285255   44.219494  13.590000 -0.000699   
1       2006-02-08   56.234295  20.198933   44.537624  12.830000 -0.000499   
2       2006-02-09   56.267998  20.388838   44.452793  13.120000  0.000599   
3       2006-02-10   56.149998  20.017660   44.544701  12.870000 -0.002097   
4       2006-02-13   56.189342  19.706907   44.343231  13.350000  0.000701   
...            ...         ...        ...         ...        ...       ...   
3745    2020-12-22  106.425888  13.624198  181.857025  24.230000  0.001443   
3746    2020-12-23  106.353706  13.794738  182.168060  23.309999 -0.000678   
3747    2020-12-24  106.452972  13.832635  182.472748  21.530001  0.000933   
3748    2020-12-28  106.470993  13.747366  183.627304  21.700001  0.000169   
3749    2020-12-29  106.489052  13.785263  182.860779  23.080000  0.000170   

Ticker     AGG_y     DBC_R     DBC_y     VTI_R     VTI_y    ^VIX_R    ^VIX_y  
0      -0.000499 -0.028926 -0.004255 -0.009737  0.007194  0.042178 -0.055923  
1       0.000599 -0.004255  0.009402  0.007194 -0.001905 -0.055923  0.022603  
2      -0.002097  0.009402 -0.018205 -0.001905  0.002068  0.022603 -0.019055  
3       0.000701 -0.018205 -0.015524  0.002068 -0.004523 -0.019055  0.037296  
4      -0.001600 -0.015524 -0.008322 -0.004523  0.009486  0.037296 -0.082397  
...          ...       ...       ...       ...       ...       ...       ...  
3745   -0.000678 -0.011004  0.012517  0.000207  0.001710 -0.036963 -0.037969  
3746    0.000933  0.012517  0.002747  0.001710  0.001673 -0.037969 -0.076362  
3747    0.000169  0.002747 -0.006164  0.001673  0.006327 -0.076362  0.007896  
3748    0.000170 -0.006164  0.002757  0.006327 -0.004174  0.007896  0.063594  
3749    0.000593  0.002757  0.006186 -0.004174  0.002691  0.063594 -0.013432  

[3750 rows x 13 columns]

In [7]:
def create_batches(dataframe, start_date, end_date, window_size=50):
    dataframe['Date'] = pd.to_datetime(dataframe['Date'])
    
    filtered_data = dataframe[(dataframe['Date'] >= start_date) & (dataframe['Date'] <= end_date)]
    
    x_batches = []
    y_batches = []
    dates_batches = []

    for i in range(len(filtered_data) - window_size):
        window_returns = filtered_data.iloc[i:i+window_size][[col for col in dataframe.columns if col.endswith('_R')]].values
        window_prices = filtered_data.iloc[i:i+window_size][[col for col in dataframe.columns if col in ['AGG', 'DBC', 'VTI', '^VIX']]].values
        
        window_x = np.concatenate([window_returns, window_prices], axis=1)
        window_y = filtered_data.iloc[i:i+window_size][[col for col in dataframe.columns if col.endswith('_y')]].values
        
        window_dates = filtered_data.iloc[i:i+window_size]['Date'].values

        x_batches.append(window_x)
        y_batches.append(window_y)
        dates_batches.append(window_dates)

    return np.array(x_batches), np.array(y_batches), np.array(dates_batches)

x_batches, y_batches, dates_batches = create_batches(data_na, start_date="2006-01-01", end_date="2010-12-31")


/var/folders/7q/v0vj3h051dn717mx7ngrr8yh0000gn/T/ipykernel_70529/944961369.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['Date'] = pd.to_datetime(dataframe['Date'])


In [8]:
print(x_batches.shape, y_batches.shape)
print(x_batches[0, :5, :])
print(y_batches[0,:5,:])

(1185, 50, 8) (1185, 50, 4)
[[-6.98955909e-04 -2.89255625e-02 -9.73666929e-03  4.21779289e-02
   5.62623634e+01  2.02852554e+01  4.42194939e+01  1.35900002e+01]
 [-4.98886658e-04 -4.25544478e-03  7.19434949e-03 -5.59234894e-02
   5.62342949e+01  2.01989326e+01  4.45376244e+01  1.28299999e+01]
 [ 5.99329118e-04  9.40174265e-03 -1.90470954e-03  2.26032707e-02
   5.62679977e+01  2.03888378e+01  4.44527931e+01  1.31199999e+01]
 [-2.09710733e-03 -1.82049451e-02  2.06753040e-03 -1.90548782e-02
   5.61499977e+01  2.00176601e+01  4.45447006e+01  1.28699999e+01]
 [ 7.00708623e-04 -1.55239357e-02 -4.52285948e-03  3.72960762e-02
   5.61893425e+01  1.97069073e+01  4.43432312e+01  1.33500004e+01]]
[[-0.00049889 -0.00425544  0.00719435 -0.05592349]
 [ 0.00059933  0.00940174 -0.00190471  0.02260327]
 [-0.00209711 -0.01820495  0.00206753 -0.01905488]
 [ 0.00070071 -0.01552394 -0.00452286  0.03729608]
 [-0.00159976 -0.00832242  0.00948555 -0.08239703]]


In [9]:
data_na.head(51)

Ticker       Date        AGG        DBC        VTI   ^VIX     AGG_R     AGG_y  \
0      2006-02-07  56.262363  20.285255  44.219494  13.59 -0.000699 -0.000499   
1      2006-02-08  56.234295  20.198933  44.537624  12.83 -0.000499  0.000599   
2      2006-02-09  56.267998  20.388838  44.452793  13.12  0.000599 -0.002097   
3      2006-02-10  56.149998  20.017660  44.544701  12.87 -0.002097  0.000701   
4      2006-02-13  56.189342  19.706907  44.343231  13.35  0.000701 -0.001600   
5      2006-02-14  56.099453  19.542898  44.763851  12.25 -0.001600  0.001101   
6      2006-02-15  56.161224  19.258041  44.933510  12.31  0.001101 -0.001000   
7      2006-02-16  56.105064  19.491108  45.283459  11.48 -0.001000  0.004107   
8      2006-02-17  56.335468  19.767332  45.230438  12.01  0.004107 -0.003691   
9      2006-02-21  56.127522  20.095350  45.103180  12.41 -0.003691  0.004004   
10     2006-02-22  56.352276  19.767332  45.456650  11.88  0.004004 -0.000598   
11     2006-02-23  56.318592  19.698277  45.343548  11.87 -0.000598  0.000798   
12     2006-02-24  56.363525  20.233463  45.414242  11.46  0.000798 -0.002094   
13     2006-02-27  56.245518  19.836390  45.545044  11.59 -0.002094  0.002098   
14     2006-02-28  56.363525  20.103985  45.096111  12.34  0.002098  0.000030   
15     2006-03-01  56.365200  20.060822  45.492004  11.54  0.000030 -0.002501   
16     2006-03-02  56.224224  20.423368  45.460186  11.72 -0.002501 -0.002006   
17     2006-03-03  56.111443  20.613270  45.385952  11.96 -0.002006 -0.005528   
18     2006-03-06  55.801258  20.285255  45.053684  12.74 -0.005528  0.002527   
19     2006-03-07  55.942268  19.931343  44.869900  12.66  0.002527  0.000505   
20     2006-03-08  55.970509  19.611954  44.997135  12.32  0.000505 -0.001311   
21     2006-03-09  55.897118  19.810495  44.756760  12.68 -0.001311  0.000403   
22     2006-03-10  55.919655  19.724173  45.106739  11.85  0.000403  0.001816   
23     2006-03-13  56.021225  19.983131  45.216301  11.37  0.001816  0.003321   
24     2006-03-14  56.207287  20.276623  45.682884  10.74  0.003321 -0.002709   
25     2006-03-15  56.055046  20.052191  45.887878  11.35 -0.002709  0.004225   
26     2006-03-16  56.291866  20.224829  45.986855  11.98  0.004225 -0.002204   
27     2006-03-17  56.167801  20.129877  46.022221  12.12 -0.002204 -0.000401   
28     2006-03-20  56.145306  19.715542  45.924969  11.79 -0.000401 -0.002613   
29     2006-03-21  55.998615  19.784597  45.669415  11.62 -0.002613  0.001812   
30     2006-03-22  56.100109  19.750071  45.946251  11.21  0.001812 -0.000803   
31     2006-03-23  56.055046  20.086718  45.935593  11.17 -0.000803  0.001710   
32     2006-03-24  56.150917  20.043556  45.995956  11.19  0.001710  0.000803   
33     2006-03-27  56.196018  20.164410  45.964005  11.46  0.000803 -0.002509   
34     2006-03-28  56.055046  20.423368  45.694279  11.58 -0.002509 -0.002012   
35     2006-03-29  55.942268  20.561478  46.120155  10.95 -0.002012 -0.004537   
36     2006-03-30  55.688484  20.811810  45.995956  11.57 -0.004537  0.003342   
37     2006-03-31  55.874573  20.665062  46.020771  11.39  0.003342 -0.000983   
38     2006-04-03  55.819630  20.760014  45.971107  11.57 -0.000983  0.001318   
39     2006-04-04  55.893227  20.647802  46.237286  11.14  0.001318  0.000709   
40     2006-04-05  55.932877  20.777279  46.407635  11.13  0.000709 -0.000809   
41     2006-04-06  55.887600  21.148457  46.386333  11.45 -0.000809 -0.003343   
42     2006-04-07  55.700787  21.053503  45.889465  12.26 -0.003343 -0.000915   
43     2006-04-10  55.649818  21.441948  45.949814  12.19 -0.000915  0.002034   
44     2006-04-11  55.763020  21.528267  45.534565  13.00  0.002034 -0.000913   
45     2006-04-12  55.712101  21.485104  45.626850  12.76 -0.000913 -0.002033   
46     2006-04-13  55.598858  21.623219  45.616215  12.38 -0.002033  0.001629   
47     2006-04-17  55.689438  21.856279  45.545216  12.58  0.001629 -0.000711   
48     2006-04-18  55.649818  2

In [10]:
mini_batch_size = 64

x_batches_tensor = torch.tensor(x_batches, dtype=torch.float32)
y_batches_tensor = torch.tensor(y_batches, dtype=torch.float32)

num_batches = x_batches_tensor.shape[0]

input_size = 8
hidden_size = 64
output_size = 4
model_lstm = ModelSharpe(input_size=input_size, hidden_size=hidden_size, output_size=output_size)


In [11]:
optimizer = torch.optim.Adam(model_lstm.parameters(), lr=0.001)
num_epochs = 100


for epoch in range(num_epochs):
    model_lstm.train()
    loss_epoch = 0
    
    for i in range(0, num_batches, mini_batch_size):
        x_mini_batch = x_batches_tensor[i:i+mini_batch_size]
        y_mini_batch = y_batches_tensor[i:i+mini_batch_size]
        
        optimizer.zero_grad()
        
        loss = model_lstm(x_mini_batch, y_mini_batch)
        loss_epoch += loss.item()
        loss.backward()
        optimizer.step()
    
    print(f"epoch [{epoch+1}/{num_epochs}], loss: {(loss_epoch/mini_batch_size)}")

#AJOUTER UNE VALIDATION (10%)

epoch [1/100], loss: -0.02079773171863053
epoch [2/100], loss: -0.030923958373023197
epoch [3/100], loss: -0.040932092582806945
epoch [4/100], loss: -0.04879126681043999
epoch [5/100], loss: -0.05226859386311844
epoch [6/100], loss: -0.05354498460656032
epoch [7/100], loss: -0.05142541437817272
epoch [8/100], loss: -0.0578384361906501
epoch [9/100], loss: -0.054337391036824556
epoch [10/100], loss: -0.058879014948615804
epoch [11/100], loss: -0.05960246729955543
epoch [12/100], loss: -0.05539454804966226
epoch [13/100], loss: -0.059767176368040964
epoch [14/100], loss: -0.06278908168314956
epoch [15/100], loss: -0.06323304109537276
epoch [16/100], loss: -0.06322519222158007
epoch [17/100], loss: -0.05862916700425558
epoch [18/100], loss: -0.06247627687116619
epoch [19/100], loss: -0.05918489710893482
epoch [20/100], loss: -0.06560766837537813
epoch [21/100], loss: -0.06514239532407373
epoch [22/100], loss: -0.06299903002218343
epoch [23/100], loss: -0.06844622158678249
epoch [24/100], 

In [12]:
def get_optimal_allocations_and_returns(model_used, dataframe, start_date, end_date, window_size=50):
    filtered_data = dataframe[(dataframe['Date'] >= start_date) & (dataframe['Date'] <= end_date)]

    x_data = []
    for i in range(len(filtered_data) - window_size):
        window_returns = filtered_data.iloc[i:i+window_size][[col for col in dataframe.columns if col.endswith('_R')]].values
        window_prices = filtered_data.iloc[i:i+window_size][[col for col in dataframe.columns if not (col.endswith('_R') or col.endswith('_y') or col == 'Date')]].values

        window_x = np.concatenate([window_returns, window_prices], axis=1)
        x_data.append(window_x)

    window_y = filtered_data.iloc[window_size:(len(filtered_data))][[col for col in dataframe.columns if col.endswith('_R')]].values

    x_tensor = torch.tensor(x_data, dtype=torch.float32)

    allocations = model_used.get_allocations(x_tensor)


    return allocations, window_y, filtered_data

#model_lstm = ModelSharpe(input_size, hidden_size, output_size)

allocations, window_y, filtered_data = get_optimal_allocations_and_returns(model_lstm, data_na, start_date="2011-01-01", end_date="2013-01-01")

/var/folders/7q/v0vj3h051dn717mx7ngrr8yh0000gn/T/ipykernel_70529/412490987.py:14: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:281.)
  x_tensor = torch.tensor(x_data, dtype=torch.float32)


In [13]:
print(allocations.shape, window_y.shape)
rt = allocations*window_y

torch.Size([452, 4]) (452, 4)


/var/folders/7q/v0vj3h051dn717mx7ngrr8yh0000gn/T/ipykernel_70529/173523728.py:2: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rt = allocations*window_y


In [14]:
rt_2 = torch.sum(rt, dim=-1)

In [15]:
rt_3 = rt_2+1
k=1
for i in range(len(rt_3)//2):
    k*=rt_3[i]
print(f'return cumulé 1 an (2011): {(k-1)*100}%', k)


return cumulé 1 an (2011): 19.404694022165092% tensor(1.1940, dtype=torch.float64)


In [16]:
rt_3 = rt_2+1
k=1
for i in range(len(rt_3)//2, len(rt_3)):
    k*=rt_3[i]
print(f'return cumulé 1 an (2012) : {(k-1)*100}%', k)


return cumulé 1 an (2012) : 27.753478093539673% tensor(1.2775, dtype=torch.float64)
